server:
  port: 8080
spring:
  application:
    name: "PruebaTecnicaNequi"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: franquiciasdb
    schema: franquicias_schema
    username: postgres
    password: postgres
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
