version: '3.3'

services:
  db:
    image: postgres:15
    container_name: postgres-db-container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: franquiciasdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d  # monta el init.sql

  app:
    image: prueba-tecnica-nequi:latest
    container_name: app-service
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres